[mongodb]
mongodb.daws88s.sbs

[redis]
redis.daws88s.sbs

[musql]
mysql.daws88s.sbs

[rabbitmq]
rabbitmq.daws88s.sbs

[frontend]
172.31.33.225

[cart]
172.31.8.193

[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321


[local:vars]
; course=ansibble
; duration=10 hrs
; trainer=kavya reddy